Use FormUrlEncodedContent to build query
loklak/LoklakDotNet pull request #4
Opened 2016-09-15 08:38 UTC by raefaldhia

2016-09-16 08:37 UTC, sudheesh001 commented on LoklakDotNet/Loklak.cs
> +                qs.Add("fields",string.Join(",",fields));
please leave a space after the `,` making it `, fields` instead of `,fields`

2016-09-16 08:37 UTC, sudheesh001 commented on LoklakDotNet/Loklak.cs
> +                qs.Add("limit",limit.ToString());
Same here, please leave a space after the `,` making it as `, limit`

2016-09-16 08:37 UTC, sudheesh001 commented on LoklakDotNet/Loklak.cs
> +                qs.Add("timeZoneOffset",timeZoneOffset.ToString());
Similar here too, `, timeZoneOffset...`

2016-09-16 08:38 UTC, sudheesh001 commented on LoklakDotNet/Loklak.cs
> +                qs.Add("color_text",color_text);
Same here `, color_text`

2016-09-16 08:38 UTC, sudheesh001 commented on LoklakDotNet/Loklak.cs
> +                qs.Add("color_background",color_background);
`, color_background`

2016-09-16 08:38 UTC, sudheesh001 commented on LoklakDotNet/Loklak.cs
> +            qs.Add("followers",follower_count.ToString());
Change this to be `, follower_count. ...` need the spacing after the `,` so that it looks more pleasing to read this.

2016-09-16 08:39 UTC, sudheesh001 requested changes

2016-09-16 11:22 UTC, raefaldhia commented
Updated

2016-10-30 06:44 UTC, jayvdb commented
@sudheesh001 ping.

2016-10-30 11:39 UTC, sudheesh001 approved these changes

2016-10-30 11:39 UTC, merged